### ISSUE TITLE
something seems to have broken in GRU

### ISSUE THREAD

**Issue by ffmpbgrnn** [andyljones/char-rnn-experiments#1]
Thank you for sharing your code. Lots of insight here! In your commit [ff06450](https://github.com/andyljones/char-rnn-experiments/commit/ff06450327d37c3c61ffe3cd0151e09682d8d7ee), it said `Adds support for single-layer GRUs, but something seems to have broken`. Does the problem still exist? Anyway, I would start to investigate your code. :-)

**Comment by andyljones** [comment]
It's fixed - or at least _cough_ it works for me.

As a heads up, the current master branch (and most of the recent experimental ones) is configured to use a GPU. The most recent commit on master which doesn't expect a GPU is [here](https://github.com/andyljones/char-rnn-experiments/commit/11a1e38acdcab3554d118ef49794fc822a06085c).

I'll try and find time <s>later today</s> (whoops, other things have come up) over the weekend to update the readme and add a rundown of how the project's structured.
